version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: mhrs_backend
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
      - rabbitmq
      - elasticsearch
    restart: always
    ports:
      - "5000:5000"

  frontend:
    image: nginx:alpine
    container_name: mhrs_frontend
    depends_on:
      - backend
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  mongodb:
    image: mongo:7.0
    container_name: mhrs_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: mhrs_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: mhrs_elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

volumes:
  mongo_data:
  elastic_data: